//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class fee
    {
        public int fee_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> class_id { get; set; }
        public string Month_ { get; set; }
        public Nullable<decimal> last_month_chrg { get; set; }
        public Nullable<decimal> total_fee { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public Nullable<decimal> paid { get; set; }
        public Nullable<decimal> remaning { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual student student { get; set; }
    }
}
