//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary
    {
        public int sal_id { get; set; }
        public Nullable<int> t_id { get; set; }
        public string month_ { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public Nullable<decimal> basic_sal { get; set; }
        public Nullable<decimal> deduction { get; set; }
        public Nullable<decimal> allowances { get; set; }
        public Nullable<decimal> advance_sal { get; set; }
        public Nullable<decimal> total_amount { get; set; }
    
        public virtual teacher teacher { get; set; }
    }
}
