//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_attendance
    {
        public int att_id { get; set; }
        public Nullable<int> std_id { get; set; }
        public Nullable<int> cls_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date_ { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual student student { get; set; }
    }
}
