//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.fees = new HashSet<fee>();
            this.student_attendance = new HashSet<student_attendance>();
        }
    
        public int std_id { get; set; }
        public string name_ { get; set; }
        public Nullable<int> f_id { get; set; }
        public Nullable<int> class_id { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<System.DateTime> admission_date { get; set; }
        public string status { get; set; }
        public string cell_no { get; set; }
        public byte[] image { get; set; }
    
        public virtual @class @class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fee> fees { get; set; }
        public virtual parent parent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student_attendance> student_attendance { get; set; }
    }
}
