//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public teacher()
        {
            this.papers = new HashSet<paper>();
            this.salaries = new HashSet<salary>();
            this.staff_attendance = new HashSet<staff_attendance>();
        }
    
        public int t_id { get; set; }
        public string emp_num { get; set; }
        public string name_ { get; set; }
        public string f_name { get; set; }
        public string subject { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<System.DateTime> join_date { get; set; }
        public string qualification { get; set; }
        public string cell_no { get; set; }
        public string cnic { get; set; }
        public string descripition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paper> papers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salary> salaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<staff_attendance> staff_attendance { get; set; }
    }
}
