//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int t_id { get; set; }
        public string type_ { get; set; }
        public Nullable<int> cls_id { get; set; }
        public Nullable<int> sub_id { get; set; }
        public Nullable<System.DateTime> date_ { get; set; }
        public string descripition { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual subject subject { get; set; }
    }
}
